[project]
name = "python-magic"
version = "0.1.0"
description = "Python lesson demonstrating mutable default arguments and type-safe solutions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.8.0",
    "ruff>=0.1.0",
    "pytest>=7.0.0"
]
